apiVersion: apps/v1
kind: Deployment
metadata: 
  name: docker-compose
  lables:
    app: docker-compose
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: docker-compose
  template: 
    metadata:
      lables:
        apps: service
    spec:
      containers:
      - name: service
        image: jordangrindrod/chaperoo-service
        ports:
        - name: service-port
          containerPort: 5000
spec:
  replicas: 1
  selector:
    matchLables:
      app: docker-db
  template:
    metadata:
      lables:
        apps: service
    spec: 
      containers:
      - name: db
        image: jordangrindrod/chaperoo-db
        ports:
      - name: db-port
          containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: docker-compose
spec:
  type: LoadBalancer
  ports: 
  - port: 80
    targetPort: 5000
  selector:
    app: docker-compose

version: "3.7"
services:
  chaperoo-client:
    image: jordangrindrod/chaperoo-client
    build: .
    ports:
      - target: 80
        published: 80
    depends_on:
      - chaperoo-service    
  chaperoo-service: 
    image: jordangrindrod/chaperoo-service
    depends_on: 
      - chaperoo-db
  chaperoo-db:
    image: jordangrindrod/chaperoo-db
    environment:
      - MYSQL_ROOT_PASSWORD=password