kind: Namespace
apiVersion: v1
metadata:
  name: nginx-app
  labels:
    name: nginx-app

---

kind: Namespace
apiVersion: v1
metadata:
  name: apache-app
  labels:
    name: apache-app

---

kind: Pod 
apiVersion: v1
metadata:
  name: nginx
  labels:
    app: nginx
  namespace: nginx-app
spec:
  containers:
  - name: nginx
    image: nginx:alpine

---

kind: Pod
apiVersion: v1
metadata:
  name: apache
  labels:
    app: apache
  namespace: apache-app
spec: 
  containers:
  - name: httpd
    image: httpd